
import java.awt.Color;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author integral-computer
 */
public class support extends javax.swing.JFrame {

    /**
     * Creates new form support
     */
    public support() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headjPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        a1 = new javax.swing.JPanel();
        l2 = new javax.swing.JLabel();
        a2 = new javax.swing.JPanel();
        l3 = new javax.swing.JLabel();
        a3 = new javax.swing.JPanel();
        a4 = new javax.swing.JPanel();
        l5 = new javax.swing.JLabel();
        a5 = new javax.swing.JPanel();
        l6 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelinfo = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headjPanel1.setBackground(new java.awt.Color(0, 0, 0));
        headjPanel1.setPreferredSize(new java.awt.Dimension(2000, 1500));
        headjPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon("F:\\netbean\\netbean project\\mini_project\\src\\mini_project\\icons8-slide-up-48.png")); // NOI18N
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        headjPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 50, 60));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 102, 0));
        jLabel22.setText("P");
        headjPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("roject");
        headjPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("rganization");
        headjPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 240, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 102, 0));
        jLabel25.setText("O");
        headjPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 40, -1));

        a1.setBackground(new java.awt.Color(0, 0, 0));
        a1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a1MouseExited(evt);
            }
        });
        a1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l2.setForeground(new java.awt.Color(240, 240, 240));
        l2.setText("HOME");
        l2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l2MouseExited(evt);
            }
        });
        a1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, -5, 50, 30));

        headjPanel1.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 70, 20));

        a2.setBackground(new java.awt.Color(0, 0, 0));
        a2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a2MouseExited(evt);
            }
        });
        a2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("FEATURE");
        l3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l3MouseExited(evt);
            }
        });
        a2.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 60, 40));

        headjPanel1.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 70, 20));

        a3.setBackground(new java.awt.Color(0, 0, 0));
        a3.setForeground(new java.awt.Color(240, 240, 240));
        a3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a3MouseExited(evt);
            }
        });
        a3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        headjPanel1.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 70, -1));

        a4.setBackground(new java.awt.Color(0, 0, 0));
        a4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a4MouseExited(evt);
            }
        });
        a4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setText("ABOUT US");
        l5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a4.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 18));

        headjPanel1.add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 80, 30));

        a5.setBackground(new java.awt.Color(0, 0, 0));
        a5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        a5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                a5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a5MouseExited(evt);
            }
        });
        a5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 102, 0));
        l6.setText("SUPPORT");
        l6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l6MouseExited(evt);
            }
        });
        a5.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        headjPanel1.add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 60, 20));

        jLabel26.setIcon(new javax.swing.ImageIcon("F:\\netbean\\netbean project\\mini_project\\src\\mini_project\\icons8-shutdown-48.png")); // NOI18N
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        headjPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 60, 60));

        l4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        l4.setForeground(new java.awt.Color(240, 240, 240));
        l4.setText("CONTACT");
        l4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l4MouseExited(evt);
            }
        });
        headjPanel1.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, 20));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        headjPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1370, 690));

        getContentPane().add(headjPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 80));

        jPanelinfo.setBackground(new java.awt.Color(255, 102, 0));
        jPanelinfo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 0, true));
        jPanelinfo.setForeground(new java.awt.Color(255, 255, 255));
        jPanelinfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("mohit@gmail.com");
        jLabel30.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelinfo.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 180, 40));

        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelinfo.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 30, 50));
        jPanelinfo.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 40, 50));

        jLabel33.setFont(new java.awt.Font("Under", 3, 48)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("CONTACT US");
        jPanelinfo.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 230, 40));

        getContentPane().add(jPanelinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 230, 410, 330));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("STARTS");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 150, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("HERE");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("HELP");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 110, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("PROJECTS  |  PROJECT INFO  |  DESIGN |  SOURCE CODE  |  ABOUT US  |  FEATURES  |  ABOUT US  |  CONTACT US ");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 1050, 60));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel28.setText("upport");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 170, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("C");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 40, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel27.setText("ustomer");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 160, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("S");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 40, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("F");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 30, 40, 40));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel29.setText("orm");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 110, 30));

        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 540, 10));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(255, 102, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("                                 READ");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 530, 50));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 560, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 1030, 10));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1370, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        this.setState(JFrame.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
        home hm=new home();
        hm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_l2MouseClicked

    private void l2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseEntered
        l2.setForeground(Color.orange);        // TODO add your handling code here:
    }//GEN-LAST:event_l2MouseEntered

    private void l2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseExited
        l2.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_l2MouseExited

    private void a1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseClicked

    }//GEN-LAST:event_a1MouseClicked

    private void a1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseEntered
        l2.setForeground(Color.orange);        // TODO add your handling code here:
        a1.setBackground(Color.gray);
    }//GEN-LAST:event_a1MouseEntered

    private void a1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a1MouseExited
        // TODO add your handling code here:
        l2.setForeground(Color.white);
        a1.setBackground(Color.black);
    }//GEN-LAST:event_a1MouseExited

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked

        features fe = new features();
        fe.setVisible(true);
        fe.pack();
        fe.setLocationRelativeTo(null);
        fe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_l3MouseClicked

    private void l3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseEntered
        l3.setForeground(Color.orange);         // TODO add your handling code here:
    }//GEN-LAST:event_l3MouseEntered

    private void l3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseExited
        l3.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_l3MouseExited

    private void a2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MouseClicked

        features fe = new features();
        fe.setVisible(true);
        fe.pack();
        fe.setLocationRelativeTo(null);
        fe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_a2MouseClicked

    private void a2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MouseEntered
        l3.setForeground(Color.orange);        // TODO add your handling code here:
        a2.setBackground(Color.gray);
    }//GEN-LAST:event_a2MouseEntered

    private void a2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MouseExited
        // TODO add your handling code here:
        l3.setForeground(Color.white);
        a2.setBackground(Color.black);
    }//GEN-LAST:event_a2MouseExited

    private void a3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_a3MouseClicked

    private void a3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3MouseEntered
        l4.setForeground(Color.orange);         // TODO add your handling code here:
        a3.setBackground(Color.gray);
    }//GEN-LAST:event_a3MouseEntered

    private void a3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a3MouseExited
        // TODO add your handling code here:
        l4.setForeground(Color.white);
        a3.setBackground(Color.black);
    }//GEN-LAST:event_a3MouseExited

    private void a4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a4MouseEntered
        // TODO add your handling code here:
        a4.setBackground(Color.gray);
    }//GEN-LAST:event_a4MouseEntered

    private void a4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a4MouseExited
        // TODO add your handling code here:
        a4.setBackground(Color.black);
    }//GEN-LAST:event_a4MouseExited

    private void l6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_l6MouseClicked

    private void l6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseEntered
        l6.setForeground(Color.orange);        // TODO add your handling code here:
    }//GEN-LAST:event_l6MouseEntered

    private void l6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseExited
        l6.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_l6MouseExited

    private void a5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a5MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_a5MouseClicked

    private void a5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a5MouseEntered
        l6.setForeground(Color.orange);        // TODO add your handling code here:
        a5.setBackground(Color.gray);
    }//GEN-LAST:event_a5MouseEntered

    private void a5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a5MouseExited
        // TODO add your handling code here:
        l6.setForeground(Color.white);
        a5.setBackground(Color.black);
    }//GEN-LAST:event_a5MouseExited

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        this.hide();
    }//GEN-LAST:event_jLabel26MouseClicked

    private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked
        contact_us  cu= new contact_us();
        cu.setVisible(true);
        this.hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_l4MouseClicked

    private void l4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseEntered
        l4.setForeground(Color.orange);        // TODO add your handling code here:
    }//GEN-LAST:event_l4MouseEntered

    private void l4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseExited
        l4.setForeground(Color.white);         // TODO add your handling code here:
    }//GEN-LAST:event_l4MouseExited

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        Thread th;
        th = new Thread(){

            public void run(){

                try{
                    for(int a=0;a<280;a++){
                        Thread.sleep(10);
                        jPanelinfo.setBounds(1500,250,a,300);

                    }
                }catch(Exception e){
                    System.out.println(e);
                }

            }

        };
        th.start();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(support.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(support.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(support.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(support.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new support().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel a1;
    private javax.swing.JPanel a2;
    private javax.swing.JPanel a3;
    private javax.swing.JPanel a4;
    private javax.swing.JPanel a5;
    private javax.swing.JPanel headjPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelinfo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    // End of variables declaration//GEN-END:variables
}
